### PR TITLE
Continuous integration build action

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This is an example of a simple continuous integration build script.  Would this be of any interest to you?

It can be expanded to also run on MacOS.

### CODE REVIEW

**Comment by marksmith** [comment]
We would be very interested, @larsbrinkhoff! Please could you provide a link to any relevant documentation on the continuous integration system that you're using so that we can confirm it meets our requirements and that we can maintain this in the future?

**Comment by larsbrinkhoff** [comment]
Here's the documentation for Actions:  
https://docs.github.com/en/free-pro-team@latest/actions

I have used Travis CI a lot, which integrates very well with GitHub but seems in decline now:  
https://docs.travis-ci.com/

There's also GitLab CI (which of course is convenient if you use GitLab), CircleCI, Appveyor, and Cirrus CI.

**Comment by marksmith** [comment]
Thanks, @larsbrinkhoff! This looks like an excellent addition. I'm still learning about GitHub's capabilities, so please give me some time to get up to speed, but I look forward to integrating this.

**Review by marksmith — APPROVED** [review]

**Comment by marksmith** [comment]
Thank you for your contribution, @larsbrinkhoff! Please forgive the delay; this was our first PR. Your additions have been merged, and as per your suggestion (above), have been expanded to run on macOS.

**Comment by larsbrinkhoff** [comment]
No problem.  Happy to help!

**Pull request merged**
